
# Font settings
[font]
#family = "Fira Code"
size = 12.0

# Window settings
[window]
padding.x = 5
padding.y = 5
dynamic_padding= true

# Colorscheme
[colors.primary]
#background = "#000000"
#foreground = "#E0E0E0"

[colors.cursor]
cursor =  "#c0c0c0"
text = "#0e0e0e"


[colors.normal]
black   = "#282828"
red     = "#af5f5f"
green   = "#5faf5f"
yellow  = "#5f5faf"
blue    = "#5f87af"
magenta = "#8787af"
cyan    = "#5fafaf"
white   = "#dcdccc"

[colors.bright]
#black   = "#1e1e1d"
red     = "#ff6f6f"
green   = "#8fdf8f"
yellow  = "#8f8fff"
blue    = "#8fafff"
magenta = "#afffff"
cyan    = "#8fffff"
white   = "#ffffff"


# Scrolling
[scrolling]
history = 10000
multiplier = 3



